- name: teste
  hosts: all
  tasks:
      - name: criar um diretorio teste
        file:
                path: teste_ansible
                state: directory
                owner: root
                group: root
                mode: 0775
